
server:
  port: 1234
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivek-shukla/ibm-fsd-000GGU/tree/master/yml/application/
  application:
    name: config-server
